name: transport
description: Riga transport timetable.
version: 1.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  location: ^1.4.1
  path_provider: ^0.4.1
  cupertino_icons: ^0.1.2
  connectivity: ^0.3.2
  auto_size_text: ^2.0.0
  shared_preferences: ^0.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
